image: node:14

before_script:
  - npm ci

stages:
  - build

mirror_swisstopo_production:
  stage: build
  script:
    - npm run mirror:swisstopo:store
  except:
    variables:
      - $CRON

raum_production:
  stage: build
  script:
    - npm run raum:store
  except:
    variables:
      - $CRON
