image: node:8
before_script:
  - npm install

stages:
  - build

indikatoren_staging:
  stage: build
  script:
    - npm run indikatoren-staging
  except:
    variables:
        - $CRON

#indikatoren_production:
#  stage: indikatoren_production
#  script:
#    - npm run indikatoren-production

#rhein_ues_weil_metadata_staging:
#  stage: rhein_ues_weil_metadata_staging
#  script:
#    - npm run rhein-ues-weil-metadata-staging

#rhein_ues_weil_metadata_production:
#  stage: rhein_ues_weil_metadata_production
#  script:
#    - npm run rhein-ues-weil-metadata-production

#rhein_ues_weil_raw_staging:
#  stage: rhein_ues_weil_raw_staging
#  script:
#    - npm run rhein-ues-weil-raw-staging

rhein_ues_weil_raw_production:
  stage: build
  script:
    - npm run rhein-ues-weil-raw-production
  only:
    variables:
        - $CRON

#rhein_ues_weil_corrected_staging:
#  stage: rhein_ues_weil_corrected_staging
#  script:
#    - npm run rhein-ues-weil-corrected-staging

#rhein_ues-weil_corrected_production:
#  stage: rhein_ues-weil_corrected_production
#  script:
#    - npm run rhein-ues-weil-corrected-production
