image: node:14

before_script:
  - npm ci

stages:
  - build

mirror_swisstopo_production:
  stage: build
  script:
    - npm run mirror:swisstopo:store
  except:
    variables:
      - $CRON

ogd_production:
  stage: build
  script:
    - npm run ogd:store
  except:
    variables:
      - $CRON

raum_production:
  stage: build
  script:
    - npm run raum:store
  except:
    variables:
      - $CRON

rhein_ues_weil_static:
  stage: build
  script:
    - npm run rhein-ues-weil:static:store
  except:
    variables:
      - $CRON

rhein_ues_weil_corrected:
  stage: build
  script:
    - npm run rhein-ues-weil:corrected:store
  only:
    variables:
      - $CRON

rhein_ues_weil_raw:
  stage: build
  script:
    - npm run rhein-ues-weil:raw:store
  only:
    variables:
      - $CRON