image: node:14

before_script:
  - npm ci

stages:
  - build

code_production:
  stage: build
  script:
    - npm run code:store
  except:
    variables:
      - $CRON

mirror_swisstopo_production:
  stage: build
  script:
    - npm run mirror:swisstopo:store
  except:
    variables:
      - $CRON

raum_production:
  stage: build
  script:
    - npm run raum:store
  except:
    variables:
      - $CRON

static:
  stage: build
  script:
    - npm run static:store
  except:
    variables:
      - $CRON

ogd_production_monthly:
  stage: build
  script:
    - npm run ogd:store:monthly
  only:
    variables:
      - $CRON
      - $CRON_MONTHLY

ogd_production_weekly:
  stage: build
  script:
    - npm run ogd:store:weekly
  only:
    variables:
      - $CRON
      - $CRON_WEEKLY

rhein_ues_weil_corrected:
  stage: build
  script:
    - npm run rhein-ues-weil:corrected:store
  only:
    variables:
      - $CRON
      - $CRON_RHEIN_UES_WEIL_CORRECTED

rhein_ues_weil_raw:
  stage: build
  script:
    - npm run rhein-ues-weil:raw:store
  only:
    variables:
      - $CRON
      - $CRON_RHEIN_UES_WEIL_RAW
